valiknet_cinema_homepage:
    path:     /{_locale}
    defaults: { _controller: ValiknetCinemaBundle:Index:show, _locale: uk}

valiknet_cinema:
    resource: "@ValiknetCinemaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    defaults: { _locale: uk }

