valiknet_movie_index:
    path: /movie/{slug}
    defaults: { _controller: ValiknetCinemaBundle:Movie:get }

valiknet_actor_last:
    path: /actor/last
    defaults: { _controller: ValiknetCinemaBundle:Actor:last }

valiknet_actor_index:
    path: /actor/{slug}
    defaults: { _controller: ValiknetCinemaBundle:Actor:get }

valiknet_director_index:
    path: /director/{slug}
    defaults: { _controller: ValiknetCinemaBundle:Director:get }

valiknet_category_index:
    path: /category/{slug}
    defaults: { _controller: ValiknetCinemaBundle:Category:index }

valiknet_country_index:
    path: /country/{slug}/{section}
    defaults: { _controller: ValiknetCinemaBundle:Country:index, section: movies }
    requirements:
      section: movies|actors|producers

valiknet_proposal_list:
  path: /proposal/list
  defaults: { _controller: ValiknetCinemaBundle:Proposal:list}

valiknet_proposal_movie:
  path: /proposal/movie
  defaults: { _controller: ValiknetCinemaBundle:Proposal:movie}

valiknet_proposal_actor:
  path: /proposal/actor
  defaults: { _controller: ValiknetCinemaBundle:Proposal:actor}

valiknet_proposal_director:
  path: /proposal/director
  defaults: { _controller: ValiknetCinemaBundle:Proposal:director}

