<?php

namespace Valiknet\CinemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoryBySlugAndSortedMovieByDate($slug)
    {
        $category = $this->getEntityManager()
                    ->getRepository('ValiknetCinemaBundle:Category')
                    ->createQueryBuilder('c')
                    ->join($this->getEntityManager()
                            ->getRepository('ValiknetCinemaBundle:Movie')
                            ->createQueryBuilder('m')
                            ->orderBy('m.releasedAt', 'DESC'),
                        'movies'
                    )
                    ->where('c.slug', $slug);

        return $category;
    }
}
